### PR TITLE
Added display current design settings on particular store

### PR DESCRIPTION
**Pull request by LukeOl**
Hi

First of all, great work guys with magerun, I can't imagine to work with Magento without Magerun :)

I have proposition of new command to Magerun pack.
I have added command to magerun, which shows current design settings on particular store view.

When developer works on Magento with one store view, he/she simply goes to configuration to obtain design settings.
If store has more than one store view, it is annoying to obtain design settings on all store views.
Command dev:theme:current will quickly show design settings to all Magento store views.

I hope this will be useful for people. I can assure you, our frontend team is pleased with this command :)

Greetz, LukeOl

### CODE REVIEW

**Comment by tkn98** [comment]
Hi @LukeOl first of all thanks for your PR! Can you rebase it on top of current develop branch first? We don't pull against `master` but against [`develop`](https://github.com/netz98/n98-magerun/tree/develop).

Github allows you to rebase your PR branch to update it with the changes or you can just close this pull request and create a new one.

Let me know if you need any more help-

**Comment by cmuench** [comment]
Thanks. I will investigate you code in the next days.

**Comment by LukeOl** [comment]
Hi, @cmuench 

Thanks for catching this misspell :) I will fix it when I apply @tkn98 suggestion.

About dev:theme:info - I have seen class InfoCommand in master/develop branch codes and based on argument "theme" in method configure() I suppose this command would display information about particular theme (like how many phtml files are, which of templates/xmls has been moved from base fallback etc).
Thats why I decided to use dev:theme:current as it shows current design settings on stores, not information about particular theme.
If dev:theme:info command is supposed to display the same information as dev:theme:current, let me know, I will move my code to InfoCommand class.

**Comment by tkn98** [comment]
@LukeOl: Just a suggestion based on your feedback and perhaps a good compromise:

A call of **`dev:theme:info`** could reveal the information of the current theme (by default).

This would allow to add a parameter later on to tell which theme to get the info about without changing the command-name.

**Comment by LukeOl** [comment]
I am closing this PR, because I have created new one, using branch develop, not master.

**Comment by tkn98** [comment]
New PR is: https://github.com/netz98/n98-magerun/pull/534

**Pull request closed without merging**
