### PR TITLE
Add command category:create:dummy (with tests)

### PR DESCRIPTION
**Pull request by giuseppemorelli**
Magerun pull-request check-list:

- [x] Pull request against develop branch (if not, just close and create a new one against it)
- [x] README.md reflects changes (if any)

Fixes # .

Changes proposed in this pull request:

This is the new PR with unit test. Same functionality as #844 
Hope it has a good code quality and merge in your future version.

Thank you!

### CODE REVIEW

**Comment by giuseppemorelli** [comment]
Hi @tkn98, do you know how I can increase code coverage in this part ?

```
if(is_null($input->getArgument('category-number'))) {
    $question = new Question("Please enter the number of categories to create (default 1): ", 1);
    $question->setValidator(function ($answer) {
        $answer = (int)($answer);
        if(!is_int($answer) || $answer <= 0) {
            throw new \RuntimeException(
                'Please enter an integer value or > 0'
            );
        }
        return $answer;

    });

    $input->setArgument('category-number', $helper->ask($input, $output, $question));
}
```

In every request of argument I don't reach code coverage and I didn't find any way to solve.
Do you have any ideas?
Thanks a lot!

**Comment by ktomk** [comment]
@giuseppemorelli: Sorry for the late reply, I'm just seeing your question. To test interactive questions you can place the input into the input-stream and give it to the question helper of the command tester: [Testing a Command that Expects Input¶](http://symfony.com/doc/current/components/console/helpers/questionhelper.html#testing-a-command-that-expects-input). You should then be able to enter in there.

**Comment by giuseppemorelli** [comment]
@ktomk Thanks for the help! I will add the tests and push the code again.

**Comment by ktomk** [comment]
The build fails with *one* Magento version (1.5.1.0). That is reproducible. Example build:

- https://travis-ci.org/netz98/n98-magerun/jobs/149215824

It would require too look into there, why this happens, but from a first glance I'd say you might be interested to learn about: [assertRegExp](https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertRegExp). But that only as another note in the margin. I must admit I have no clue why it fails with that Magento version *only*. Weird.

**Comment by giuseppemorelli** [comment]
@ktomk I don't know why but in Magento 1.5.1 if you create a category with specific store view you have to include also admin store view.

For **assertRegExp**: Actually I'm studing it but I have to learn more. Do you mean to avoid preg_match function in the code? I tried to find a function to get data with regular expression (for checking category id created) but I didn't find anything else.
Any ideas? Thank you for your support!

Ps. All checks have passed, do you need something else to complete this PR?

**Comment by tkn98** [comment]
If it's green, it's beautiful :) :+1: for assertRegExp, yes it should spare you the preg_match call, so that you can assert against the regular expression directly.

**Pull request merged**
