### PR TITLE
Update for new standard phpstorm.meta used by the JetBrains/phpstorm-stubs library

### PR DESCRIPTION
**Pull request by boesbo**
Update for new standard phpstorm.meta used by the JetBrains/phpstorm-stubs library:
https://github.com/JetBrains/phpstorm-stubs

I replaced the "$STATIC_METHOD_TYPES[]" wrapper with the "override()" method.

#### Fixes:
https://github.com/netz98/n98-magerun/issues/1140

### CODE REVIEW

**Comment by cmuench** [comment]
@boesbo Thanks. Seems that the automated test of the command is currently failing.

**Comment by boesbo** [comment]
> @boesbo Thanks. Seems that the automated test of the command is currently failing.
It is failing due to build issues:
"The job exceeded the maximum log length, and has been terminated."

**Comment by boesbo** [comment]
> @boesbo Thanks. Seems that the automated test of the command is currently failing.

It is failing due to build issues:
> The job exceeded the maximum log length, and has been terminated.

**Comment by cmuench** [comment]
@boesbo :-) nice try.
The test is failing, then the differences are printed. The differences are a way too long for travis-ci.

**Comment by boesbo** [comment]
> @boesbo :-) nice try.
> The test is failing, then the differences are printed. The differences are a way too long for travis-ci.

You're right, now I'm trying to find what he doesn't like

**Comment by boesbo** [comment]
@cmuench Now only the magento-lts test fails. The problem is that it finds `'core / mysql4_design_theme_collection' => \ Mage_Core_Model_Mysql4_Design_Theme_Collection`

and it is among the `assertNotContains`, do you have any idea why it shouldn't be there?

**Comment by cmuench** [comment]
@boesbo I am not so deep in the current changes of the OpenMage LTS project. I guess that the old MySQL4 classes are refactored.
Maybe @Schrank or @Flyingmana can answer this question.

**Comment by boesbo** [comment]
> @boesbo I am not so deep in the current changes of the OpenMage LTS project. I guess that the old MySQL4 classes are refactored.
> Maybe @Schrank or @Flyingmana can answer this question.

My mistake, that assert has been removed. I was not aligned

**Pull request merged**
