### PR TITLE
chore: add database setting to matrix

### PR DESCRIPTION
**Pull request by DanielRuf**
Magerun pull-request check-list:

- [x] Pull request against develop branch (if not, just close and create a new one against it)
- [ ] README.md reflects changes (if any)

Changes proposed in this pull request:

- add the missing database setting to the build matrix

### CODE REVIEW

**Comment by ktomk** [comment]
@DanielRuf: It should not be missing, see the global section it has it.

**Comment by DanielRuf** [comment]
Search for `magento-mirror-1.4.2.0" INSTALL_SAMPLE_DATA=yes` in the last Travis CI build matrix of the result page and you'll see the 5.5 entry.

**Comment by ktomk** [comment]
If it didn't work any longer, the global key should be cleaned up now, it's then superfluous.

**Comment by DanielRuf** [comment]
> If it didn't work any longer, the global key should be cleaned up now, it's then superfluous.

Not sure, I'm not aware that the global en setting was deprecated but it is not used for the matrix exclusion part afaik.

**Comment by ktomk** [comment]
what I meant, from review of the _whole_ file, we don't use it any longer, so it can be removed. if it's even deprecated, this explains somehow that it's not working in exclusion any longer. just move it out ;).

Really, safe to remove in my eyes, just double-checked it.

**Pull request merged**
