### PR TITLE
PHP 5.6 Travis

### PR DESCRIPTION
**Pull request by rafaelstz**

### CODE REVIEW

**Comment by tkn98** [comment]
@rafaelstz: Thanks for the new PR. Can you please rebase you changes on top of current HEAD develop? Right now the merge has conflicts that need resolution.

**Comment by tkn98** [comment]
@rafaelstz: Please let me know if you need more feedback or assistance with that.

**Comment by rafaelstz** [comment]
Thanks for the feedback, is right now? Can I make a new PR like that?

**Comment by tkn98** [comment]
@rafaelstz: It would now merge, but: As a pull-request in it's own is a request to merge, we normally do not want it to contain commits that are merge commits as well.

So instead, please undo the merge, fetch the changes (you should already have them as you used them in the merge) and *rebase* your your changes on top of it.

It perhaps is easily possible with a:

     $ git rebase netz98/develop

but you have to see your own. if not, you can abort a rebase operation in case you got stuck.

in case you loose the origin SHA-hash of your changes: [0b491d59bcffab1f8e22dd41a94bb01572c9bdd3](https://github.com/rafaelstz/n98-magerun/commit/0b491d59bcffab1f8e22dd41a94bb01572c9bdd3)

Do you know what *rebase* does in Git? If not, there is an introduction here: https://git-scm.com/book/en/v1/Git-Branching-Rebasing  and here: http://git-scm.com/docs/git-rebase . Also please just ask.

**Comment by tkn98** [comment]
Forgot to say: You will see merge conflicts again in the rebase. You technically resolve them as you did for the merge.

**Comment by ktomk** [comment]
To have traction on this, it needs to be rebased onto develop and the code that is highlighted by the tests that fail need to be made interoperable with PHP 5.6 as well.

**Comment by ktomk** [comment]
This PR went stale. Additionally PHP 5.6 is supported in the travis build currently, so I'll close it.

**Pull request closed without merging**
