### PR TITLE
Use compressed sample-data

### PR DESCRIPTION
**Pull request by sreichel**
Magerun pull-request check-list:

- [x] Pull request against develop branch (if not, just close and create a new one against it)
- [x] README.md reflects changes (if any)

Subject: (50 characters or less)

Use 95MB compressed sample data instead of current 430MB.

I'v just compressed mp3 to 48k and reduced image quality to 50%.  It's not as optimized as https://github.com/Vinai/compressed-magento-sample-data yet, but that's coming. (Eventually.)

---

I tried `tar.xz` (~50MB) but install sample data fails with ...
```

  [UnexpectedValueException]                                                                                                                                    
  internal corruption of phar "/home/sr/workspace/tests/n98/magento/_temp_demo_data/3b521eeeb430578bc0efd3d2876d834a.xz" (__HALT_COMPILER(); not found)  
```

### CODE REVIEW

**Comment by ktomk** [comment]
From the error it looks like that PHPs Phar can't open it. IIRC .tar.xy requires xz extension at least, the error might go away then but I have not tested it.

**Comment by sreichel** [comment]
@ktomk  `xz` seem unsupported (yet) - https://bugs.php.net/bug.php?id=63880. Please ignore this.

**Comment by cmuench** [comment]
@sreichel @ktomk is that xz extension topic a blocker?

**Comment by ktomk** [comment]
No @cmuench

**Comment by sreichel** [comment]
@cmuench no blocker.

**Pull request merged**
