### PR TITLE
Adding a prompt when unlocking all admin users.

### PR DESCRIPTION
**Pull request by brobie**
There have been numerous time that I run this command, expecting a prompt for a username to be entered, and it simply unlocks all users.  I have added a prompt to make sure that the intention is to unlock everyone.

### CODE REVIEW

**Comment by brobie** [comment]
I did not mean to commit the phar file. I will fix and resubmit in the morning.

**Comment by ktomk** [comment]
@brobie: Thank you for your PR! You can squash this into one commit and just remove the phar file from it, no problem. I also left a little comment about visibility and code-style of the method name, feel free to change that as well. When you build the phar using `build.sh` it should normally not be marked as changed in git, the phing build marks it as assume-unchanged IIRC.

**Comment by tkn98** [comment]
@brobie: We can't pull the changes if you close it, please take a look :)

**Comment by brobie** [comment]
I will reopen another one. I wanted to be able to create another request. I
wasn't sure how to squash and remove the phar file from my forked repo.
Don't worry it will get there. :)

**Comment by tkn98** [comment]
No problem at all! Melting commits together, incl. removing files from commit that were done can be explained :) Feel free to ask or otherwise do just like you see fit.

Hint: If you change your existing branch (or with the same name a new one) and push it, this PR should get updated.

**Pull request closed without merging**
