### PR TITLE
Add command category:create:dummy

### PR DESCRIPTION
**Pull request by giuseppemorelli**
Magerun pull-request check-list:

- [X] Pull request against develop branch (if not, just close and create a new one against it)
- [X] README.md reflects changes (if any)

Subject: Add command category:create:dummy

Fixes # .

Changes proposed in this pull request:

- Add command to create dummy category  (category:create:dummy)
- Actually the category has a fixed name with progress id because I didn't find a specific class in Faker library

You can find other info in my magerun-addons:  https://github.com/gmdotnet/GMdotnet_MagerunAddons

Thank you!

### CODE REVIEW

**Comment by tkn98** [comment]
Thanks for creating a Pull-Request. Unfortunately the Circle-CI Build did hang, I just restarted it.

**Comment by tkn98** [comment]
Please squash your commits into one (you can force-push to the feature branch to update his PR). Also please take care that text-files have a newline at the end of file.

**Comment by tkn98** [comment]
@giuseppemorelli: Just raise your voice if you want support / feedback. It would be great adding some test coverage for your PR.

**Comment by giuseppemorelli** [comment]
Hi @tkn98, I've just created a single commit as you described. I don't understand if you want a feature branch or a new PR here in develop branch.
Please, let me know how I can send this new feature.
Thank you very much!

**Comment by tkn98** [comment]
For a Github PR a specifically named "feature" branch is not required. A branch on your end you say you want to create a PR from is just enough :) So everything is fine about the branch :)

Do you consider to add some tests to increase the coverage again? We're falling below 70% with this PR.

**Comment by giuseppemorelli** [comment]
You're right about tests, I'm working on it. So, I think is better to close this PR. I will send you a new PR with all requisites discussed today to get a better code.

**Comment by tkn98** [comment]
@giuseppemorelli  It would have been fine to keep this PR, but we can also deal with the new one :) Force-Pushes do automatically update the PR, so everything can be kept in one place. But no problem, let's just deal with #845 for this one :) Thanks for the tests!

**Comment by giuseppemorelli** [comment]
@tkn98 sorry about that. I didn't know about PR automatic update. I keep it for the future. :)

**Pull request closed without merging**
