### PR TITLE
Adds sys:version command

### LINKED ISSUE #564: Magento Version
I'm patching a lot of magentos at the moment and it would be super helpful to have a command to just get the magento version. I expected magerun already has this built in but can't find it :)

### PR DESCRIPTION
**Pull request by davidalger**
Implements a sys:version command to allow grabbing the version of a Magento installation without fully bootstrapping the Magento application. This complements sys:info which requires a live database connection be present to work.

Resolves #564

### CODE REVIEW

**Comment by tkn98** [comment]
Thanks for the PR. Please re-file it as a pull-request against the **develop** branch. We don't accept PR's against *master* branch.

I close this PR here for now, because AFAIK you can't change the target branch with a Github PR. Just create a new PR against the **develop** branch. I'll cross-reference this later.

If you need any help or more feedbacl, just let me know.

**Comment by cmuench** [comment]
Please use `sys:info` command to print the current version.

**Comment by davidalger** [comment]
@tkn98 Oop… meant to PR against develop. I'll redo it pending the discussion on the open issue.

@redshark1802 Is the trailing blank-line supposed to be the standard? Just want to make sure. I usually include it, but was mimicking what I saw elsewhere in the tool. I'll update them before a new PR is submitted.

@cmuench I'll followup on the referenced issue

**Comment by tkn98** [comment]
@davidalger: newline at the end of file is standard. not all code is in a good shape, so we say it explicitly for new PRs :)

**Comment by davidalger** [comment]
@tkn98 cool, thx. will keep it in mind moving forward. :)

**Pull request closed without merging**
