### PR TITLE
Change config init to Magento's reinit function

### LINKED ISSUE #583: Redis and reached 100 router match iterations problem after cache:clean
Did anyone find a problem on running cache:clean with some option, e.g:
n98-magerun.phar cache:clean block_html
n98-magerun.phar cache:clean eav layout
with Redis and Cm_Cache_Backend_Redis module? After that kind of operation I got " Front controller reached 100 router match iterations". It looks like main routers (Admin, Standard) are not on the list anymore. What's more curious when I run
n98-magerun.phar cache:clean
...it works and I can get my store without any error anymore.

I think it could be connected with AbstractCacheCommand.php->reinitCache()
\Mage::getConfig()->loadModules()->loadDb()->saveCache();

### PR DESCRIPTION
**Pull request by DuckThom**
Applies the change suggested in the comments of issue https://github.com/netz98/n98-magerun/issues/583

Magerun pull-request check-list:

- [x] Pull request against develop branch (if not, just close and create a new one against it)
- [x] README.md reflects changes (if any)

Subject:

Fixes #583 

Changes proposed in this pull request:

- Changes the config init logic to Magento's own reinit function in the Config model to prevent issues with the `CONFIG` cache tag being cleared without being rebuilt when using the Redis cache storage engine.

### CODE REVIEW

**Comment by cmuench** [comment]
@DuckThom Thanks for your PR. Your commit reverts some lines of code which were introduced to prevent a race condition.
We added that code in 2015.
https://github.com/netz98/n98-magerun/issues/483

We have to check if that really fixes the problem without creating a regression bug.

**Comment by DuckThom** [comment]
@cmuench I see, I tested this change on my local environment yesterday and I did not find any issues running the `cache:clean` command after the change and the issues I was having were fixed.

While debugging my issue yesterday I came across this repo [AmpersandHQ/magento-ce-ee-config-corruption-bug](https://github.com/AmpersandHQ/magento-ce-ee-config-corruption-bug ) which describes the bug the lines removed in this PR were causing. 

Magento created a fix for it, but these removed lines were bypassing that fix. By calling `reinit` on the Config model it will match Magento's cache reinitialisation logic and include the bugfix. (See the latest 2 comments on 583 by convenient and mseliger-dotsource). Or do you mean a different race condition?

**Comment by cmuench** [comment]
@DuckThom I had never had this issue with the race condition. As I imagine was the problem in combination with Redis and a huge amount of data.
For me it's getting harder and harder to track all the issue because the most of our projects are running on Magento 2.
In Magento 2 I can see some changes according to cache locking issues.
In which release was can I find this cache fix you mentioned?

**Comment by DuckThom** [comment]
@cmuench Me neither, the project I was working on was the first one I saw having this issue as well and it's quite a large project so there is a lot of config data involved.

From what I've read, the fix was released in 1.9.3.1.

**Pull request merged**
