### PR TITLE
Update readme with compare-versions changes

### PR DESCRIPTION
**Pull request by convenient**
https://github.com/netz98/n98-magerun/pull/789

See changes in above PR.

Update the readme to match.

### CODE REVIEW

**Comment by ktomk** [comment]
Manually merged fast-forward into develop. I just wanted to release 1.97.12 but there is a problem with the automated build. But a tagged stable release is close :)

**Comment by ktomk** [comment]
@convenient: [Magerun 1.97.12 is out](http://magerun.net/released-n98-magerun-version-1-97-12/) with the exit status changes. 1.97.13 will have the readme change as well, but we still have a problem so just FYI and it will come :).

**Comment by convenient** [comment]
Amazing! Thank you very much @ktomk .

Weird, did I confuse things by using the same branch for the readme change?

**Comment by ktomk** [comment]
@convenient: Even if it was the same branch this was no problem at all as I was able to cherry-pick it with easy. See the updated develop (and master for that matter).

**Comment by tkn98** [comment]
@convenient 1.97.13 is out now ;)

**Pull request closed without merging**
