### PR TITLE
Autocompletion for oh-my-zsh

### PR DESCRIPTION
**Pull request by joh-klein**

### CODE REVIEW

**Comment by cmuench** [comment]
Thanks

**Comment by nntoan** [comment]
Is there anyway to show description of commands like n98-magerun list ?

**Comment by cmuench** [comment]
@nntoan 
n98-magerun is based on Symfony console component. So you can use `n98-magerun.phar list` to list all commands.
Every command has a `--help` option to provide more infos about options and arguments.

**Comment by nntoan** [comment]
@cmuench
I mean show description in when type n98-magerun.phar [TAB] like when you type git [TAB]
I want exactly like that in oh-my-zsh

**Comment by joh-klein** [comment]
@nntoan I'll have a look, shouldn't be to hard.

**Pull request merged**
