### PR TITLE
Add Homebrew installation

### PR DESCRIPTION
**Pull request by mgeoffray**
Magerun pull-request check-list:

- [v ] Pull request against develop branch (if not, just close and create a new one against it)
- [ v] README.md reflects changes (if any)

Subject: (50 characters or less)

Fixes # .

Changes proposed in this pull request:

- Add Homebrew installation

### CODE REVIEW

**Comment by tkn98** [comment]
@mgeoffray: Thanks for filing a pull request. If you see Travis red, it's not related to your PR, just saying. I have to fix the develop branch for the build, you can squash and rebase your commits then.

**Comment by mgeoffray** [comment]
Hi @tkn98   
I did not understand, I have to make the PR later when the develop branch will be fixed ?

**Comment by mgeoffray** [comment]
Hi @tkn98 
OK no problem I will make these changes during the day. Thank you.

**Comment by mgeoffray** [comment]
@tkn98 squashing is done, I have just pushed. Please notice that the PR on homebrew-php are not accepted yet.

**Comment by tkn98** [comment]
@mgeoffray; Noted. Also please take notice that I haven't fixed the build yet ^^

**Comment by ktomk** [comment]
@mgeoffray: I could fix the develop build. If you could rebase on top of the current develop and update this PR, the build then should show green.

**Comment by mgeoffray** [comment]
@ktomk Done, looks good now!

**Comment by mgeoffray** [comment]
Hi,
n98-magerun is officialy available from homebrew https://github.com/Homebrew/homebrew-php/blob/master/Formula/n98-magerun.rb

**Comment by ktomk** [comment]
@mgeoffray: Formidable! Please see my comment over in the MR2 PR :+1:

**Pull request merged**
