### PR TITLE
Update lookup command

### PR DESCRIPTION
**Pull request by tomasliubinas**
Documentation update proposal

### CODE REVIEW

**Comment by tkn98** [comment]
Thanks

**Comment by cmuench** [comment]
@tkn98  ui... a master merge.

**Comment by tkn98** [comment]
@cmuench: o_O ... Hotfix ;) - I'll take care of it later.

**Comment by ktomk** [comment]
@cmuench Has been reverted in master.

**Comment by ktomk** [comment]
The documentation update will be in the next release and is not part of the development version. Thanks!

**Pull request merged**
