### PR TITLE
Add option to schedule cron in magento crontab instead of running

### PR DESCRIPTION
**Pull request by gillg**
Magerun pull-request check-list:

- [X] Pull request against develop branch (if not, just close and create a new one against it)
- [X] README.md reflects changes (if any)

Subject: (50 characters or less)

Add option to schedule cron in magento crontab instead of running. This avoid running with right problems, and follow all magento native workflow.
More clean in most cases.

### CODE REVIEW

**Comment by cmuench** [comment]
@gillg Thanks for your PR. At the moment it looks like the commit is breaking a lot of unit tests.
The output is `Option mode "Schedule cron instead of run with current user" is not valid.`.
Could it be that the order of the parameters is not valid?

**Comment by gillg** [comment]
Sorry I made a big mistake in parameters order ! It's corrected.

**Comment by cmuench** [comment]
@gillg Thanks. The tests are now back again. Can you please send the PR against the develop branch? We do not merge directly to master branch.

https://github.com/netz98/n98-magerun/wiki/Contribution-Process

**Comment by gillg** [comment]
Done ! :)

**Comment by cmuench** [comment]
@gillg Thanks

**Pull request merged**
