### PR TITLE
[TASK] Added js and css merging commands

### PR DESCRIPTION
**Pull request by sippsolutions**
@tkn98

### CODE REVIEW

**Comment by sippsolutions** [comment]
@tkn98 I just fixed the mess.

**Comment by ktomk** [comment]
Thanks for refreshing the PR. There is a lot of duplicate code, please take a look to reduce it.

**Comment by sippsolutions** [comment]
Hi @ktomk, I don't really see any duplicate code in here :)

**Comment by ktomk** [comment]
hi @sippsolutions: Both tests look nearly identical, just some parameters changed.

**Comment by sippsolutions** [comment]
I copied the Test from TemplateHintsCommandTest and changed the parameters, so it should be ok (imho)

**Comment by ktomk** [comment]
Yes, thank you for your contribution! :+1:  (We so desperately need more tests so we accept anything we can get :D - just kidding a bit, please see I already striked that sentence just a moment I commented)

A style thing for next time: For the commit messages we establish a new style to use active, commanding verbs in front, not the past form (here: *add* instead of *added*). Just FYI for the next time, it's not yet established as you can see with older messages.

Thanks for flying with magerun. You will see the development version updated soon. And your changes will be part of the next stable release whenever it will be released.

**Comment by tkn98** [comment]
@sippsolutions: Are you okay having your full name in credits? Just asking, put it in there yesterday privately in develop, but think I should have asked you first.

**Comment by sippsolutions** [comment]
@tkn98 No problem, it's fine!

**Pull request merged**
