### PR TITLE
#806 Move all N98\Util to the shared folder, use composer (dual usage)

### PR DESCRIPTION
**Pull request by amenk**
The shared folder is included via composer, so it can be used as
before but also required via composer to other projects (dual usage)

- all N98\Util classes including their tests are moved to the shared
  folder
- add composer.json to the util folder, move autoload there
- require the shared folder

### CODE REVIEW

**Comment by amenk** [comment]
Tests should work now, but build.sh still fails:

    PHP Fatal error:  Uncaught Error: Class 'N98\Util\ArrayFunctions' not found in phar:///home/self/imi/workspace/n98-magerun/build/output/n98-magerun.phar/src/N98/Magento/Application/Config.php:310
Stack trace:

no clue why ...

**Comment by cmuench** [comment]
@amenk Can you change the indentation level of your comment? :-P

**Comment by amenk** [comment]
done.. hopefully :-) I should have a precommit hook...

**Comment by ktomk** [comment]
@amenk: git subrepo =/= composer, just in case this went under. https://github.com/ingydotnet/git-subrepo

**Comment by amenk** [comment]
​Yes I know. In my PR it is still autoloaded the same way as before. The
composer.json is just "for myself" to include it via composer. It does not
interfere with the rest of magerun.

**Comment by amenk** [comment]
So what's the plan?

**Comment by ktomk** [comment]
From my end git subrepo.

**Comment by amenk** [comment]
That you did already, right? It is still the same, the composer.json should
not hurt. Autoloading is the way you did it. I just moved all the N98\Util
to the shared folder and fixed some issues.

After you accept the PR should should be able to push to the subrepo?
​

**Comment by ktomk** [comment]
Can you squash, polish and rebase the commits so that it is easier to review?

**Comment by amenk** [comment]
sure, done

**Comment by ktomk** [comment]
Thanks. in my opinion this is not needed and mistakes the meaning of the shared folder. I decline the PR.

You can achieve the same by using magerun as a remote for the package you would like to create and handle this via subtree merge. That will also allow you to apply patches and stay more independent.

**Comment by amenk** [comment]
But you already started to move stuff to shared/ --- why not the full
N98\Util ? Which problems does it generate? I could also sync with magerun2
if you'd like...
But subtree split / merge might be an option, will think about it.

**Comment by ktomk** [comment]
Yes, please checkout the subtree merging . I don't do it that often, but have this with some projects in which I need to keep track of upstream changes but I do have local changes as well.

It generates problems in that we package in here but we don't. So this contradicts. The shared folder actually is not used to extract the utils, at least not that way you do it here. So what you try to achieve with this PR might be what you want, but there is no implication for the project to have it. You need more freedom here and more control, and for contradicting things this would always cause problems.

If it's externatlized you can decide what you need for your packaging (building etc.) and what should be pushed back upstream.

Right now we already have the problem of the deviation between the mr1+2 repos. It originally was one but somehow it got cutted in half. The shared folder is a  mitigation of that while keeping the repos independent. Creating a package here wouldn't do that.

So please try if utils folder will do it for you. And sorry if that is at a different pace. From what I sense, I can imagine that it's also better for you to have more control.

**Comment by amenk** [comment]
I think I would need more like to do a subtree split and then could make a composer module out of it.

     git subtree split --prefix src/N98/Util/ -b n98-util-split

Unfortunately I need two folders - also the shared one :-( So I have to use filter branch ... will see ...

**Comment by amenk** [comment]
Here we go ... https://github.com/iMi-digital/n98-utils-split

**Pull request closed without merging**
