### PR TITLE
Changed hardcoded autoload.php to dynamic

### PR DESCRIPTION
**Pull request by JeroenBoersma**
Read the guidelines carefully :)

* changed hardcoded location to defined PHPUNIT_COMPOSER_INSTALL

### CODE REVIEW

**Comment by JeroenBoersma** [comment]
Linked with ticket #780

**Comment by robbieaverill** [comment]
What benefit does this add to the project?

**Comment by JeroenBoersma** [comment]
@robbieaverill Projects are individually tested, so if I want to test my new command in a magerun addon I would love to make use of existing code.

The problem a ran into was that without this I cannot use this testcase and need to copy it over too my own project, which imho not the way to go.

With this I can easily test all my addons in the same way you did.
So, basically it benefits the project by having testcases too for magerun addons which are tested in the same way.

**Comment by cmuench** [comment]
Thanks

**Comment by robbieaverill** [comment]
Very nice!

On Thursday, 3 March 2016, Christian Münch <notifications@github.com> wrote:

> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/netz98/n98-magerun/pull/782#issuecomment-191666448>.
>


-- 
*Robbie Averill*
LA PETITE MANOUCHE - NZ Gypsy Jazz Guitar Duo
Phone: +64 27 321 4758
contact@lapetitemanouche.com
www.lapetitemanouche.com

**Pull request merged**
