### PR TITLE
Adding OpenMage Magento LTS 1.9.4.x

### PR DESCRIPTION
**Pull request by sreichel**
Magerun pull-request check-list:

- [x] Pull request against develop branch (if not, just close and create a new one against it)
- [x] README.md reflects changes (if any)

Add latest version to installer.

### CODE REVIEW

**Comment by ktomk** [comment]
@sreichel I somewhat think the number of non-versioned packages is a sanity check in the test-case. IIRC I added it really some time ago.

If there was removal of a version in this PR which still should be supported (but was removed due to the falling test as the commit msg suggests), raise the number as needed in the test.

The failing test should only remind not to add non-versions by accident (syntax of a version) or in case the version detection breaks, so self-check of the test.

**Comment by sreichel** [comment]
@ktomk My guess was you don want to limit it intenionally. :)

"mageplus" is based on Magento 1.7 and not maintained anymore. Still keep it? Lts 1.9.3.x should just be removed in favour of 1.9.4.x. (1.9.3.x just gets official patches merged, all other PRs are for 1.9.4.x only)  ... Please let me know if I should re-add "mageplus".

**Comment by ktomk** [comment]
If it is still available for download, I'd say it's OK to keep, e.g. if there are any users who have this in CI or similar processing. If not re-added, these would break, that is not so nice then.

Do you know it can still be installed via Magerun?

**Comment by sreichel** [comment]
@ktomk  No, I dont know. Re-added and changed test.

**Comment by sreichel** [comment]
OpenMage does not update 1.9.3.x branch anymore .... if you're okay with, i'd add a PR to remove it.

**Comment by cmuench** [comment]
@sreichel ok

**Pull request merged**
