### PR TITLE
Fixed workflow

### PR DESCRIPTION
**Pull request by sreichel**
Magerun pull-request check-list:

- [x] Pull request against develop branch (if not, just close and create a new one against it)
- [x] README.md reflects changes (if any)

Fixes broken workflow for v.20.1+

### CODE REVIEW

**Comment by sreichel** [comment]
@cmuench oh no :( Guess the bootstrap file has to take care of COMPOSER_VENDOR_PATH, but i've no time today. Can you take a look at it?

**Comment by cmuench** [comment]
@sreichel Great! Looks like you fixed the technical issue of the ci pipeline.
And we found some new issues with PHP 8.2 by running the tests. :+1:

**Comment by sreichel** [comment]
@cmuench i dont think its only related to php8.2 ... see linked issue.

**Comment by cmuench** [comment]
> @cmuench i dont think its related to php8.2 ... see linked issue.

@sreichel If the issue is in OpenMage then it's nice that we could find this here.
IMHO we can merge the changes here to develop branch and then wait for a fix in MageOS ... and then update the CI config to install the fixed versions.
What do you mean?

**Comment by sreichel** [comment]
@cmuench merging to develop should be okay. Maybe you want to test install-command in local environment before. Maybe i've missed something.

**Comment by cmuench** [comment]
@sreichel LGTM

**Pull request merged**
