### PR TITLE
Add support for multi module declaration files.

### PR DESCRIPTION
**Pull request by pocallaghan**
Mage allows multiple modules to be declared in the same file in
app/etc/modules, however the old code didn't support this. Search
for the last included file that includes the declartion for the
passed module name.

Magerun pull-request check-list:

- [ ] Pull request against develop branch (if not, just close and create a new one against it)
- [ ] README.md reflects changes (if any)

Subject: (50 characters or less)

Fixes # .

Changes proposed in this pull request:

- ...

- ...

- ...

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thanks. Fixes #961

**Comment by ktomk** [comment]
@pocallaghan Thanks for the PR, there are two minor issues with the code-style. If you could ammend the commit and force-push the PR, this should fix it. See details on the Travis build, you can also make PHP CS-Fixer fix it on your dev-box in case you don't want to do this manually.

**Comment by pocallaghan** [comment]
Amusingly both appear to be in the method that's pretty much copied from core :) I'll try and sort this later and force-push as you say.

**Comment by cmuench** [comment]
Thx

**Pull request merged**
