### PR TITLE
Command info design settings develop

### PR DESCRIPTION
**Pull request by LukeOl**
Hi @tkn98 
I closed my previous PR and I have created new one. This time I used develop branch, instead of master branch.

Here I pasted content from previous PR:
First of all, great work guys with magerun, I can't imagine to work with Magento without Magerun :)

I have proposition of new command to Magerun pack.
I have added command to magerun, which shows current design settings on particular store view.

When developer works on Magento with one store view, he/she simply goes to configuration to obtain design settings.
If store has more than one store view, it is annoying to obtain design settings on all store views.
Command dev:theme:current will quickly show design settings to all Magento store views.

I hope this will be useful for people. I can assure you, our frontend team is pleased with this command :)

Greetz, LukeOl

### CODE REVIEW

**Comment by tkn98** [comment]
Your pull request contains changes not done by yourself. This normally signals an error. Please rebase your changes against the current development branch.

Old PR was: https://github.com/netz98/n98-magerun/pull/531

**Comment by LukeOl** [comment]
Hm... I did commit from my computer at work. Authors data are a bit different from github account one, but I can assure you I did this commit :)
I can remove my commit and commit with Authors appropriate to my github accounts data if it is crucial. 

I have checked n98-magerun repo develop branch, and my forked repo branch has latest code of your repo develop branch.
I am not follow what I have did wrong.... :\

**Comment by pocallaghan** [comment]
I believe it's because you have made the pull request against master, not develop. Thus all the commits on develop are showing, not just yours.

**Comment by LukeOl** [comment]
Darn, OK
Is there a way to change PR to develop, not master?

If no, then I will close this PR and create new one with correct settings...

**Comment by tkn98** [comment]
@LukeOl at what @pocallaghan said.

You need to close the pull request (I do this for you) and create a new one. When you create the new one you have to specify the `develop` branch as where to pull against (target branch).

My fault I didn't see this earlier. ignore my previous comment, sorry for the mislead.

**Pull request closed without merging**
