### PR TITLE
added 1.9.3.0 to config.yaml

### PR DESCRIPTION
**Pull request by sylink**
Magerun pull-request check-list:

- [ ] Pull request against develop branch (if not, just close and create a new one against it)
- [ ] README.md reflects changes (if any)

Subject: Add 1.9.3.0 to installer

Fixes - Config.yaml updated to included 1.9.3.0 from the magento mirrors, handy to have.

### CODE REVIEW

**Comment by tkn98** [comment]
Thanks a lot for your PR. Please let me know what do you think about waiting until 1.9.3.1 comes out as we have a kind of warning to not update to 1.9.3.0? IIRC 1.9.3.1 is expected at the end of the week.

**Comment by sylink** [comment]
We (we being a Magento host) use the random other versions all the time for various things so its nice to be able to call them down through n98. So I'd leave both in if possible - i.e. everything the Magento mirror repo has.

Probably it could be written to automatically know that somehow, but easier to just update a config file :)

As it stands we did this in the mean time with the ~/.n98-magerun.yaml for added commands -
`commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: 1.9.3.0
        version: 1.9.3.0
        source:
          url: https://github.com/OpenMage/magento-mirror.git
          type: git
          reference: 1.9.3.0
        extra:
          sample-data: sample-data-1.9.1.0`

**Comment by tkn98** [comment]
Well actually it would be a nice idea to have some kind of provider / creator for entries based on OpenMage. So far we don't have a repository for it. But the local file as you updated it :)

**Comment by joshuaswarren** [comment]
We also use random versions as well - we need both 1.9.3.0 and the upcoming 1.9.3.1 available. I actually just submitted my own pull request for this, as I didn't see this one was already open. Having this available ASAP would be great, and then add 1.9.3.1 whenever it's released.

**Comment by ktomk** [comment]
We believe that the issue reported is handled in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.

Ref: 47de2d6ea25ec963b8d58894d508d81bd662d2e3

**Pull request closed without merging**
