### PR TITLE
PHP 7.4/8 compatibility (OpenMage 20.x)

### LINKED ISSUE #1133: PHP 7.4/8 support (OpenMage 20.x)
## Feature description

I read https://github.com/netz98/n98-magerun/issues/1014 and in the end it was fixed. Are you interested in a PHP 7.4/8 PR?

## Problem and motivation
MageOne is offering Magento Support for 7.3 and 7.4 is on the roadmap and other vendors do that as well. n98-magerun is a brilliant tool to assist us in all kinds of stuff, so maintaining it, so we don't get spammed with error messages is helpful for us.

## Is this something you're interested in working on
Yes

### PR DESCRIPTION
**Pull request by cmuench**
Magerun pull-request check-list:

- [X] Pull request against develop branch (if not, just close and create a new one against it)
- [X] README.md reflects changes (if any)

Subject: PHP 8.1 compatibility

Fixes #1133
See Checklist: #1275

Changes proposed in this pull request:

- Upgrade Symfony to 4.4
- Upgrade PHPUnit to 9.x
- Supress deprecation warnings (to be compatible with PHP 7.4)
- Drop support for PHP <7.4
- Test CI with OpenMage 20.
- Backport classes from n98-magerun2
- Optimize code style

### CODE REVIEW

**Comment by sreichel** [comment]
@cmuench Added a PR to your repo.

**Comment by colinmollenhour** [comment]
This is a huge PR, kudos for the hard work! Is it in working condition? Anything holding up the merge?

**Comment by cmuench** [comment]
@colinmollenhour the installer is broken. If the installer works then we see the test results. My gut feeling is that we will find some minor todos then.
Sadly I have not enough energy to finish the PR.
In the daily business I do work with M1 anymore for years.

**Comment by sreichel** [comment]
@cmuench @colinmollenhour installer is fixed. Sample data needs some work and some unit tests have to be fixed. I've also no time at the moment.

edit: installer works only for OpenMage (???)

**Comment by colinmollenhour** [comment]
Perhaps this PR could be merged and tagged in it's current state as `2.4.0-beta1` or `3.0.0-beta1`? Would be a shame if this sat unused for a long time..

**Comment by cmuench** [comment]
@colinmollenhour @sreichel I just reviewed.
our are right @sreichel. The installer was already fixed.
Currently we have 48 broken tests.
Example job log: https://github.com/cmuench/n98-magerun/actions/runs/5119227073/job/13852779165#step:10:608

**Comment by cmuench** [comment]
> Perhaps this PR could be merged and tagged in it's current state as `2.4.0-beta1` or `3.0.0-beta1`? Would be a shame if this sat unused for a long time..

Some commands seem to be broken. So it's not 100% compatible at the moment.

**Comment by sreichel** [comment]
Another problem is that there are no tagged releases for Magento 1.x

**Comment by cmuench** [comment]
> Another problem is that there are no tagged releases for Magento 1.x

You mean a tag for n98-magerun?

**Comment by sreichel** [comment]
No, magento-mirror has no composer installable releases.

So atm it only works for OM. (or did I missed something?)

**Comment by sreichel** [comment]
@colinmollenhour i would not like a release at current state. Seems I've missed one or two commands that can be easily fixed.

UnitTests v9 seems no big deal, but I've no time for.

**Comment by sreichel** [comment]
@cmuench nice :) maybe I've some time during next days.

**Pull request merged**
