### PR TITLE
Tested

### PR DESCRIPTION
**Pull request by rafaelstz**

### CODE REVIEW

**Comment by ktomk** [comment]
@rafaelstz: Thank you for your PR. Could you please add PHP 5.6 to the [`.travis.yml`](https://github.com/netz98/n98-magerun/blob/develop/.travis.yml) file? This will ensure we cover PHP 5.6 in continuous integration (CI) as well. I think this is a nice addition and keeps the documentation aligned to the concrete tests.

Let me know if you run into any problems with that. You can put this all into one commit and force-push to update the PR.

**Comment by rafaelstz** [comment]
Ready! https://github.com/netz98/n98-magerun/pull/628

**Comment by ktomk** [comment]
@rafaelstz Please update the PR here (#626), there is no need to create a new PR for every file changed.

**Comment by rafaelstz** [comment]
@ktomk Ready, thanks!

**Comment by tkn98** [comment]
@rafaelstz: Thanks for all your feedback. Can you squash this into one commit please? And sorry for the delays in feedback, I think it's the timezones.

**Comment by rafaelstz** [comment]
https://github.com/netz98/n98-magerun/pull/637

**Pull request closed without merging**
